{"name": "Login using credentials with a valid password", "status": "failed", "statusDetails": {"message": "AssertionError: Failure reason: Error\nassert False", "trace": "tests/trajector/test_manual.py:122: in single_test\n    raise e\ntests/trajector/test_manual.py:115: in single_test\n    step()\ntests/trajector/test_manual.py:107: in step_for_test\n    assert answer, f\"Failure reason: {reason_of_failure}\"\nE   AssertionError: Failure reason: Error\nE   assert False"}, "description": "Login to user portal using an existing user credentials with a valid password\n", "steps": [{"name": "Open an user portal", "status": "failed", "statusDetails": {"message": "AssertionError: Failure reason: Error\nassert False\n", "trace": "  File \"/Users/maq/git/trajector-cloud-tests/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/maq/git/trajector-cloud-tests/tests/trajector/test_manual.py\", line 107, in step_for_test\n    assert answer, f\"Failure reason: {reason_of_failure}\"\n"}, "start": 1697809942641, "stop": 1697809950520}], "start": 1697809942641, "stop": 1697809951367, "uuid": "8f328b4d-6735-4a88-b44a-9904a2a5035d", "historyId": "39559ea0f91d99482e932e55e05ad87f", "testCaseId": "39559ea0f91d99482e932e55e05ad87f", "fullName": "tests.trajector.test_manual.TestExample#test_existing_user_login_with_valid_password", "labels": [{"name": "severity", "value": "TRIVIAL"}, {"name": "feature", "value": "Login"}, {"name": "suite", "value": "User portal login"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "wip"}, {"name": "tag", "value": "manual"}, {"name": "parentSuite", "value": "tests.trajector"}, {"name": "subSuite", "value": "TestExample"}, {"name": "host", "value": "trajector.local"}, {"name": "thread", "value": "41961-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.trajector.test_manual"}]}